fo = open("foo.txt", "a")
# print(dir(fo))
fo.write( "\nsdddddddddddddd")
# print ("Name of the file: ", fo.name)
# print ("Closed or not : ", fo.closed)
# print ("Opening mode : ", fo.mode)
fo.close()